Repository Broccoli-Velog/Broccoli-Backend, pull requests merged in 2022-08, with the labels that each got.

#15 PR : dev 환경변수 이슈 해결. 글목록 조회, 글 조회 기능 간단 구현
  package.json
  src/database/note.js
  src/routes/controllers/note.js
  src/routes/routers/note.js
Labels: add, refactor

#16 PR : 에러 수정을 위한 리팩토링 진행
  ENV.md
  sql/default.sql
  src/index.js
  src/models/_.loader.js
  src/models/env/env.js
  src/models/iterator/class.iterator.js
  src/modules/_.loader.js
  src/modules/providers/bcrypt.provider.js
  src/modules/providers/database.provider.js
  src/modules/providers/env.provider.js
  src/modules/providers/jwt.provider.js
  src/routes/controllers/auth.js
  src/server.js
Labels: bug, add, refactor

#18 Refactor : 기존의 `database/index.js` 파일에서 `DatabaseProvider` 를 사용하는 것으로 변경
  src/models/_.loader.js
  src/models/comment/comment.joi.js
  src/modules/_.loader.js
  src/modules/middlewares/token.guard.js
  src/modules/providers/jwt.provider.js
  src/routes/controllers/auth.js
  src/routes/controllers/comment.js
  src/routes/controllers/note.js
  src/routes/routers/comment.js
Labels: refactor

#19 PR : database 폴더 사용 안하게 다시 구현
  src/routes/controllers/note.js
Labels: add

#22 PR : `_.export.js` 파일 추가를 통한 코드 정리
  README.md
  docs/api/API-auth-명세서.md
  docs/api/API-comment-명세서.md
  docs/api/API-명세서.md
  docs/infra/BRANCHES.md
  sql/broccoli_comment.sql
  sql/broccoli_post.sql
  sql/broccoli_user.sql
  src/database/comment.js
  src/database/index.js
  src/database/note.js
  src/index.js
  src/models/comment/comment.joi.js
  src/models/env/base.env.js
  src/models/env/bcrypt.env.js
  src/models/env/database.env.js
  src/models/env/token.env.js
  src/models/user/user.joi.js
  src/modules/providers/database.provider.js
  src/routes/controllers/_.export.js
  src/routes/controllers/auth.js
  src/routes/controllers/comment.js
  src/routes/controllers/note.js
  src/routes/controllers/user.js
  src/routes/routers/_.export.js
  src/routes/routers/auth.js
  src/routes/routers/comment.js
  src/routes/routers/note.js
  src/routes/routers/user.js
  src/server.js
Labels: refactor

#23 PR : `_.export.js` 파일 추가를 통한 코드 정리
  src/index.js
  src/models/comment/comment.joi.js
  src/models/env/base.env.js
  src/models/env/bcrypt.env.js
  src/models/env/database.env.js
  src/models/env/token.env.js
  src/models/user/user.joi.js
  src/modules/providers/database.provider.js
  src/routes/controllers/_.export.js
  src/routes/controllers/auth.js
  src/routes/controllers/comment.js
  src/routes/controllers/note.js
  src/routes/controllers/user.js
  src/routes/routers/_.export.js
  src/routes/routers/auth.js
  src/routes/routers/comment.js
  src/routes/routers/note.js
  src/routes/routers/user.js
  src/server.js
Labels: add, refactor

#24 PR : 내 정보 보기/수정/탈퇴 구현
  docs/api/API-auth-명세서.md
  docs/api/API-comment-명세서.md
  docs/api/API-명세서.md
  src/models/user/user.joi.js
  src/routes/controllers/auth.js
  src/routes/routers/auth.js
Labels: add

#26 PR : 글 수정 삭제 기능 구현 및 글 상세 조회 시 댓글 목록도 응답
  f
  src/routes/controllers/note.js
  src/routes/routers/note.js
Labels: add

#28 PR : `f` 파일 삭제 후 병합 dev/unchaptered > submain
  .gitignore
  docs/api/API-auth-명세서.md
  docs/api/API-comment-명세서.md
  docs/api/API-명세서.md
  src/models/user/user.joi.js
  src/modules/middlewares/token.guard.js
  src/routes/controllers/auth.js
  src/routes/controllers/note.js
  src/routes/routers/auth.js
  src/routes/routers/note.js
Labels: bug
